/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as EpgRouteImport } from './routes/epg'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordingsRulesRouteImport } from './routes/recordings.rules'
import { Route as RecordingsIdRouteImport } from './routes/recordings/$id'
import { Route as LiveChannelIdRouteImport } from './routes/live/$channelId'
import { Route as RecordingsRulesNewRouteImport } from './routes/recordings.rules.new'
import { Route as RecordingsRulesIdRouteImport } from './routes/recordings.rules.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const EpgRoute = EpgRouteImport.update({
  id: '/epg',
  path: '/epg',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRulesRoute = RecordingsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => RecordingsRoute,
} as any)
const RecordingsIdRoute = RecordingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecordingsRoute,
} as any)
const LiveChannelIdRoute = LiveChannelIdRouteImport.update({
  id: '/live/$channelId',
  path: '/live/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRulesNewRoute = RecordingsRulesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RecordingsRulesRoute,
} as any)
const RecordingsRulesIdRoute = RecordingsRulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecordingsRulesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epg': typeof EpgRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/live/$channelId': typeof LiveChannelIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/recordings/rules': typeof RecordingsRulesRouteWithChildren
  '/recordings/rules/$id': typeof RecordingsRulesIdRoute
  '/recordings/rules/new': typeof RecordingsRulesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epg': typeof EpgRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/live/$channelId': typeof LiveChannelIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/recordings/rules': typeof RecordingsRulesRouteWithChildren
  '/recordings/rules/$id': typeof RecordingsRulesIdRoute
  '/recordings/rules/new': typeof RecordingsRulesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epg': typeof EpgRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/live/$channelId': typeof LiveChannelIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/recordings/rules': typeof RecordingsRulesRouteWithChildren
  '/recordings/rules/$id': typeof RecordingsRulesIdRoute
  '/recordings/rules/new': typeof RecordingsRulesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/epg'
    | '/recordings'
    | '/settings'
    | '/live/$channelId'
    | '/recordings/$id'
    | '/recordings/rules'
    | '/recordings/rules/$id'
    | '/recordings/rules/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/epg'
    | '/recordings'
    | '/settings'
    | '/live/$channelId'
    | '/recordings/$id'
    | '/recordings/rules'
    | '/recordings/rules/$id'
    | '/recordings/rules/new'
  id:
    | '__root__'
    | '/'
    | '/epg'
    | '/recordings'
    | '/settings'
    | '/live/$channelId'
    | '/recordings/$id'
    | '/recordings/rules'
    | '/recordings/rules/$id'
    | '/recordings/rules/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpgRoute: typeof EpgRoute
  RecordingsRoute: typeof RecordingsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  LiveChannelIdRoute: typeof LiveChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epg': {
      id: '/epg'
      path: '/epg'
      fullPath: '/epg'
      preLoaderRoute: typeof EpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/rules': {
      id: '/recordings/rules'
      path: '/rules'
      fullPath: '/recordings/rules'
      preLoaderRoute: typeof RecordingsRulesRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/recordings/$id': {
      id: '/recordings/$id'
      path: '/$id'
      fullPath: '/recordings/$id'
      preLoaderRoute: typeof RecordingsIdRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/live/$channelId': {
      id: '/live/$channelId'
      path: '/live/$channelId'
      fullPath: '/live/$channelId'
      preLoaderRoute: typeof LiveChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/rules/new': {
      id: '/recordings/rules/new'
      path: '/new'
      fullPath: '/recordings/rules/new'
      preLoaderRoute: typeof RecordingsRulesNewRouteImport
      parentRoute: typeof RecordingsRulesRoute
    }
    '/recordings/rules/$id': {
      id: '/recordings/rules/$id'
      path: '/$id'
      fullPath: '/recordings/rules/$id'
      preLoaderRoute: typeof RecordingsRulesIdRouteImport
      parentRoute: typeof RecordingsRulesRoute
    }
  }
}

interface RecordingsRulesRouteChildren {
  RecordingsRulesIdRoute: typeof RecordingsRulesIdRoute
  RecordingsRulesNewRoute: typeof RecordingsRulesNewRoute
}

const RecordingsRulesRouteChildren: RecordingsRulesRouteChildren = {
  RecordingsRulesIdRoute: RecordingsRulesIdRoute,
  RecordingsRulesNewRoute: RecordingsRulesNewRoute,
}

const RecordingsRulesRouteWithChildren = RecordingsRulesRoute._addFileChildren(
  RecordingsRulesRouteChildren,
)

interface RecordingsRouteChildren {
  RecordingsIdRoute: typeof RecordingsIdRoute
  RecordingsRulesRoute: typeof RecordingsRulesRouteWithChildren
}

const RecordingsRouteChildren: RecordingsRouteChildren = {
  RecordingsIdRoute: RecordingsIdRoute,
  RecordingsRulesRoute: RecordingsRulesRouteWithChildren,
}

const RecordingsRouteWithChildren = RecordingsRoute._addFileChildren(
  RecordingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpgRoute: EpgRoute,
  RecordingsRoute: RecordingsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  LiveChannelIdRoute: LiveChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
