/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as EpgRouteImport } from './routes/epg'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveChannelIdRouteImport } from './routes/live/$channelId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const EpgRoute = EpgRouteImport.update({
  id: '/epg',
  path: '/epg',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveChannelIdRoute = LiveChannelIdRouteImport.update({
  id: '/live/$channelId',
  path: '/live/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epg': typeof EpgRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/live/$channelId': typeof LiveChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epg': typeof EpgRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/live/$channelId': typeof LiveChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epg': typeof EpgRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/live/$channelId': typeof LiveChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/epg' | '/recordings' | '/settings' | '/live/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/epg' | '/recordings' | '/settings' | '/live/$channelId'
  id:
    | '__root__'
    | '/'
    | '/epg'
    | '/recordings'
    | '/settings'
    | '/live/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpgRoute: typeof EpgRoute
  RecordingsRoute: typeof RecordingsRoute
  SettingsRoute: typeof SettingsRoute
  LiveChannelIdRoute: typeof LiveChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epg': {
      id: '/epg'
      path: '/epg'
      fullPath: '/epg'
      preLoaderRoute: typeof EpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$channelId': {
      id: '/live/$channelId'
      path: '/live/$channelId'
      fullPath: '/live/$channelId'
      preLoaderRoute: typeof LiveChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpgRoute: EpgRoute,
  RecordingsRoute: RecordingsRoute,
  SettingsRoute: SettingsRoute,
  LiveChannelIdRoute: LiveChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
