/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as EpgRouteImport } from './routes/epg'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordingsIndexRouteImport } from './routes/recordings.index'
import { Route as RecordingsRulesRouteImport } from './routes/recordings.rules'
import { Route as RecordingsReservationsRouteImport } from './routes/recordings.reservations'
import { Route as RecordingsPendingRouteImport } from './routes/recordings.pending'
import { Route as RecordingsFailedRouteImport } from './routes/recordings.failed'
import { Route as RecordingsCompletedRouteImport } from './routes/recordings.completed'
import { Route as RecordingsIdRouteImport } from './routes/recordings/$id'
import { Route as LiveChannelIdRouteImport } from './routes/live/$channelId'
import { Route as RecordingsRulesIndexRouteImport } from './routes/recordings.rules.index'
import { Route as RecordingsRulesNewRouteImport } from './routes/recordings.rules.new'
import { Route as RecordingsRulesIdRouteImport } from './routes/recordings.rules.$id'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const EpgRoute = EpgRouteImport.update({
  id: '/epg',
  path: '/epg',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordingsRoute,
} as any)
const RecordingsRulesRoute = RecordingsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => RecordingsRoute,
} as any)
const RecordingsReservationsRoute = RecordingsReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => RecordingsRoute,
} as any)
const RecordingsPendingRoute = RecordingsPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => RecordingsRoute,
} as any)
const RecordingsFailedRoute = RecordingsFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => RecordingsRoute,
} as any)
const RecordingsCompletedRoute = RecordingsCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => RecordingsRoute,
} as any)
const RecordingsIdRoute = RecordingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecordingsRoute,
} as any)
const LiveChannelIdRoute = LiveChannelIdRouteImport.update({
  id: '/live/$channelId',
  path: '/live/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRulesIndexRoute = RecordingsRulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordingsRulesRoute,
} as any)
const RecordingsRulesNewRoute = RecordingsRulesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RecordingsRulesRoute,
} as any)
const RecordingsRulesIdRoute = RecordingsRulesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecordingsRulesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epg': typeof EpgRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/live/$channelId': typeof LiveChannelIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/recordings/completed': typeof RecordingsCompletedRoute
  '/recordings/failed': typeof RecordingsFailedRoute
  '/recordings/pending': typeof RecordingsPendingRoute
  '/recordings/reservations': typeof RecordingsReservationsRoute
  '/recordings/rules': typeof RecordingsRulesRouteWithChildren
  '/recordings/': typeof RecordingsIndexRoute
  '/recordings/rules/$id': typeof RecordingsRulesIdRoute
  '/recordings/rules/new': typeof RecordingsRulesNewRoute
  '/recordings/rules/': typeof RecordingsRulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epg': typeof EpgRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/live/$channelId': typeof LiveChannelIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/recordings/completed': typeof RecordingsCompletedRoute
  '/recordings/failed': typeof RecordingsFailedRoute
  '/recordings/pending': typeof RecordingsPendingRoute
  '/recordings/reservations': typeof RecordingsReservationsRoute
  '/recordings': typeof RecordingsIndexRoute
  '/recordings/rules/$id': typeof RecordingsRulesIdRoute
  '/recordings/rules/new': typeof RecordingsRulesNewRoute
  '/recordings/rules': typeof RecordingsRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epg': typeof EpgRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/live/$channelId': typeof LiveChannelIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/recordings/completed': typeof RecordingsCompletedRoute
  '/recordings/failed': typeof RecordingsFailedRoute
  '/recordings/pending': typeof RecordingsPendingRoute
  '/recordings/reservations': typeof RecordingsReservationsRoute
  '/recordings/rules': typeof RecordingsRulesRouteWithChildren
  '/recordings/': typeof RecordingsIndexRoute
  '/recordings/rules/$id': typeof RecordingsRulesIdRoute
  '/recordings/rules/new': typeof RecordingsRulesNewRoute
  '/recordings/rules/': typeof RecordingsRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/epg'
    | '/recordings'
    | '/settings'
    | '/status'
    | '/live/$channelId'
    | '/recordings/$id'
    | '/recordings/completed'
    | '/recordings/failed'
    | '/recordings/pending'
    | '/recordings/reservations'
    | '/recordings/rules'
    | '/recordings/'
    | '/recordings/rules/$id'
    | '/recordings/rules/new'
    | '/recordings/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/epg'
    | '/settings'
    | '/status'
    | '/live/$channelId'
    | '/recordings/$id'
    | '/recordings/completed'
    | '/recordings/failed'
    | '/recordings/pending'
    | '/recordings/reservations'
    | '/recordings'
    | '/recordings/rules/$id'
    | '/recordings/rules/new'
    | '/recordings/rules'
  id:
    | '__root__'
    | '/'
    | '/epg'
    | '/recordings'
    | '/settings'
    | '/status'
    | '/live/$channelId'
    | '/recordings/$id'
    | '/recordings/completed'
    | '/recordings/failed'
    | '/recordings/pending'
    | '/recordings/reservations'
    | '/recordings/rules'
    | '/recordings/'
    | '/recordings/rules/$id'
    | '/recordings/rules/new'
    | '/recordings/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpgRoute: typeof EpgRoute
  RecordingsRoute: typeof RecordingsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  LiveChannelIdRoute: typeof LiveChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epg': {
      id: '/epg'
      path: '/epg'
      fullPath: '/epg'
      preLoaderRoute: typeof EpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/'
      fullPath: '/recordings/'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/recordings/rules': {
      id: '/recordings/rules'
      path: '/rules'
      fullPath: '/recordings/rules'
      preLoaderRoute: typeof RecordingsRulesRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/recordings/reservations': {
      id: '/recordings/reservations'
      path: '/reservations'
      fullPath: '/recordings/reservations'
      preLoaderRoute: typeof RecordingsReservationsRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/recordings/pending': {
      id: '/recordings/pending'
      path: '/pending'
      fullPath: '/recordings/pending'
      preLoaderRoute: typeof RecordingsPendingRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/recordings/failed': {
      id: '/recordings/failed'
      path: '/failed'
      fullPath: '/recordings/failed'
      preLoaderRoute: typeof RecordingsFailedRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/recordings/completed': {
      id: '/recordings/completed'
      path: '/completed'
      fullPath: '/recordings/completed'
      preLoaderRoute: typeof RecordingsCompletedRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/recordings/$id': {
      id: '/recordings/$id'
      path: '/$id'
      fullPath: '/recordings/$id'
      preLoaderRoute: typeof RecordingsIdRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/live/$channelId': {
      id: '/live/$channelId'
      path: '/live/$channelId'
      fullPath: '/live/$channelId'
      preLoaderRoute: typeof LiveChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/rules/': {
      id: '/recordings/rules/'
      path: '/'
      fullPath: '/recordings/rules/'
      preLoaderRoute: typeof RecordingsRulesIndexRouteImport
      parentRoute: typeof RecordingsRulesRoute
    }
    '/recordings/rules/new': {
      id: '/recordings/rules/new'
      path: '/new'
      fullPath: '/recordings/rules/new'
      preLoaderRoute: typeof RecordingsRulesNewRouteImport
      parentRoute: typeof RecordingsRulesRoute
    }
    '/recordings/rules/$id': {
      id: '/recordings/rules/$id'
      path: '/$id'
      fullPath: '/recordings/rules/$id'
      preLoaderRoute: typeof RecordingsRulesIdRouteImport
      parentRoute: typeof RecordingsRulesRoute
    }
  }
}

interface RecordingsRulesRouteChildren {
  RecordingsRulesIdRoute: typeof RecordingsRulesIdRoute
  RecordingsRulesNewRoute: typeof RecordingsRulesNewRoute
  RecordingsRulesIndexRoute: typeof RecordingsRulesIndexRoute
}

const RecordingsRulesRouteChildren: RecordingsRulesRouteChildren = {
  RecordingsRulesIdRoute: RecordingsRulesIdRoute,
  RecordingsRulesNewRoute: RecordingsRulesNewRoute,
  RecordingsRulesIndexRoute: RecordingsRulesIndexRoute,
}

const RecordingsRulesRouteWithChildren = RecordingsRulesRoute._addFileChildren(
  RecordingsRulesRouteChildren,
)

interface RecordingsRouteChildren {
  RecordingsIdRoute: typeof RecordingsIdRoute
  RecordingsCompletedRoute: typeof RecordingsCompletedRoute
  RecordingsFailedRoute: typeof RecordingsFailedRoute
  RecordingsPendingRoute: typeof RecordingsPendingRoute
  RecordingsReservationsRoute: typeof RecordingsReservationsRoute
  RecordingsRulesRoute: typeof RecordingsRulesRouteWithChildren
  RecordingsIndexRoute: typeof RecordingsIndexRoute
}

const RecordingsRouteChildren: RecordingsRouteChildren = {
  RecordingsIdRoute: RecordingsIdRoute,
  RecordingsCompletedRoute: RecordingsCompletedRoute,
  RecordingsFailedRoute: RecordingsFailedRoute,
  RecordingsPendingRoute: RecordingsPendingRoute,
  RecordingsReservationsRoute: RecordingsReservationsRoute,
  RecordingsRulesRoute: RecordingsRulesRouteWithChildren,
  RecordingsIndexRoute: RecordingsIndexRoute,
}

const RecordingsRouteWithChildren = RecordingsRoute._addFileChildren(
  RecordingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpgRoute: EpgRoute,
  RecordingsRoute: RecordingsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  LiveChannelIdRoute: LiveChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
